### ISSUE TITLE
Refactoring login, register, profiling page

### ISSUE THREAD

**Issue by Tokenzrey** [Tokenzrey/PBKKLARAVEL#1]
<img src="https://github.com/user-attachments/assets/22420d98-4ea6-43ca-8ce1-db719f75a0d2" width="300" height="200" alt="Description">

- [x] Mengubah warna backgorund button ke `#00B4D8`
- [x] Mengubah border ketika focus ke input form ke warna `#00B4D8`
- [x] Mengubah logo laravel dengan icon berikut

<img src="https://github.com/user-attachments/assets/c798ee62-ece5-429f-9442-2a897235a449" width="300" height="300" alt="Description">

- [x] pada register page, gunakan base warna untuk beberapa component/tag dengan warna `#00B4D8`
- [ ] pada profiling page, tampilkan data dari user
       - nama
       - jenis_kelamin
       - no_telepon
       - alamat
       - username
       - gambar
       - email 
- [ ] pada profiling page, user bisa mengupdate datanya sendiri, bisa upate password juga
- [ ] letak views ada di `resources/views/auth/`
- [ ] untuk profile page ada di `{url}/profile`
